Issue #836
Issue:
Build on windows report the following warings/error which further
down the stream causes regression test failures.

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Cause:
String passed to python weren't correctly escaped.

Resolution:
Switched to using forward slashes when dealing with paths to avoid
platform specific issues.